#!/bin/sh
#
#    ATerm -- The ATerm (Annotated Term) library
#    Copyright (C) 1998-2000  Stichting Mathematisch Centrum, Amsterdam, 
#                             The  Netherlands.
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
PROGRAM=java
CLASS=
NAME=
TBHOST= 
PORT=
TID=

VERBOSE=

usage="$0 -TB_TOOL_NAME <name> -TB_HOST <host> -TB_PORT <port> -TB_TOOL_ID <tid> -TB_VERBOSE -class <class> -program <prog>"

while :
do
	case "$1" in
		-TB_TOOL_NAME)	NAME="-TB_TOOL_NAME $2" ;shift;shift
				;;
		-TB_HOST)	TBHOST="-TB_HOST $2" ;shift;shift
				;;
		-TB_PORT)	PORT="-TB_PORT $2" ;shift;shift
				;;
		-TB_TOOL_ID)	TID="-TB_TOOL_ID $2" ;shift;shift
				;;
		-TB_VERBOSE)	VERBOSE="-TB_VERBOSE" ;shift
				;;
		-program)	PROGRAM=$2 ;shift;shift
				;;	
		-class)		CLASS=$2; shift; shift
				;;
		-arg)		ARGS="$ARGS $2" ;shift;shift
				;;
		-details)	DETAILS=$2; shift;shift
				;;
		-java-args)	shift; SCRIPTARGS="-args $@" ;shift;shift;shift;shift;shift;shift;shift;shift;shift;shift;shift;shift;shift
				;;
		-*)		$echo "unknown option: $1"
				$echo "$usage" >&2
				exit 1
				;;
		*) break
	esac
done

#echo "exec: $PROGRAM $ARGS $CLASS $NAME $TBHOST $PORT $TID $VERBOSE $TRACE"
$PROGRAM $ARGS $CLASS $NAME $TBHOST $PORT $TID $VERBOSE $TRACE $SCRIPTARGS

