/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_Grammar_Syntax1_1sym ;
static ATerm lf_AUX_Grammar_Syntax1_1 ( ) ;
static Symbol lf_AUX_Grammar_Syntax1_2sym ;
static ATerm lf_AUX_Grammar_Syntax1_2 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol lf_AUX_Grammar_Syntax1_3sym ;
static ATerm lf_AUX_Grammar_Syntax1_3 ( ATerm arg1 ) ;
void register_AUX_Grammar_Syntax1 ( ) {
lf_AUX_Grammar_Syntax1_1sym = ATmakeSymbol ( "prod(id(\"Grammar-Syntax\"),w(\"\"),[ql(\"(/)\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Grammar\"),w(\"\"),no-attrs)"
 , 0 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Grammar_Syntax1_1sym ) ;
lf_AUX_Grammar_Syntax1_2sym = ATmakeSymbol ( "prod(id(\"Grammar-Syntax\"),w(\"\"),[sort(\"Grammar\"),w(\"\"),sort(\"Grammar\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Grammar\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"assoc\")],w(\"\"),l(\"}\")))" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Grammar_Syntax1_2sym ) ;
lf_AUX_Grammar_Syntax1_3sym = ATmakeSymbol ( "prod(id(\"Grammar-Syntax\"),w(\"\"),[ql(\"(\"),w(\"\"),sort(\"Grammar\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Grammar\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"bracket\")],w(\"\"),l(\"}\")))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Grammar_Syntax1_3sym ) ;
register_prod ( ATparse ( "prod(id(\"Grammar-Syntax\"),w(\"\"),[ql(\"(/)\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Grammar\"),w(\"\"),no-attrs)" ) , lf_AUX_Grammar_Syntax1_1 , lf_AUX_Grammar_Syntax1_1sym ) ;
register_prod ( ATparse ( "prod(id(\"Grammar-Syntax\"),w(\"\"),[sort(\"Grammar\"),w(\"\"),sort(\"Grammar\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Grammar\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"assoc\")],w(\"\"),l(\"}\")))" ) , lf_AUX_Grammar_Syntax1_2 , lf_AUX_Grammar_Syntax1_2sym ) ;
register_prod ( ATparse ( "prod(id(\"Grammar-Syntax\"),w(\"\"),[ql(\"(\"),w(\"\"),sort(\"Grammar\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Grammar\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"bracket\")],w(\"\"),l(\"}\")))" ) , lf_AUX_Grammar_Syntax1_3 , lf_AUX_Grammar_Syntax1_3sym ) ;
}
void resolve_AUX_Grammar_Syntax1 ( ) {
}
void init_AUX_Grammar_Syntax1 ( ) {
}
ATerm lf_AUX_Grammar_Syntax1_3 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Grammar_Syntax1_3sym , ATmakeAppl ( lf_AUX_Grammar_Syntax1_3sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Grammar_Syntax1_3sym , arg0 ) ) ;
}
ATerm lf_AUX_Grammar_Syntax1_2 ( ATerm arg0 , ATerm arg1 ) {
CONS_ENTRY ( lf_AUX_Grammar_Syntax1_2sym , ATmakeAppl ( lf_AUX_Grammar_Syntax1_2sym , arg0 , arg1 ) ) ;
CONS_EXIT ( make_nf2 ( lf_AUX_Grammar_Syntax1_2sym , arg0 , arg1 ) ) ;
}
ATerm lf_AUX_Grammar_Syntax1_1 ( ) {
CONS_ENTRY ( lf_AUX_Grammar_Syntax1_1sym , ATmakeAppl0 ( lf_AUX_Grammar_Syntax1_1sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_AUX_Grammar_Syntax1_1sym ) ) ;
}

