/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_Kernel_Sdf_Syntax1_1sym ;
static ATerm lf_AUX_Kernel_Sdf_Syntax1_1 ( ATerm arg1 ) ;
static Symbol lf_AUX_Kernel_Sdf_Syntax1_3sym ;
static ATerm lf_AUX_Kernel_Sdf_Syntax1_3 ( ATerm arg1 ) ;
static Symbol lf_AUX_Kernel_Sdf_Syntax1_2sym ;
static ATerm lf_AUX_Kernel_Sdf_Syntax1_2 ( ATerm arg1 ) ;
static Symbol lf_AUX_Kernel_Sdf_Syntax1_4sym ;
static ATerm lf_AUX_Kernel_Sdf_Syntax1_4 ( ATerm arg1 , ATerm arg2 , ATerm arg3 ) ;
static Symbol lf_AUX_Kernel_Sdf_Syntax1_5sym ;
static ATerm lf_AUX_Kernel_Sdf_Syntax1_5 ( ) ;
static Symbol lf_AUX_Kernel_Sdf_Syntax1_7sym ;
static ATerm lf_AUX_Kernel_Sdf_Syntax1_7 ( ATerm arg1 ) ;
static Symbol lf_AUX_Kernel_Sdf_Syntax1_6sym ;
static ATerm lf_AUX_Kernel_Sdf_Syntax1_6 ( ATerm arg1 ) ;
void register_AUX_Kernel_Sdf_Syntax1 ( ) {
lf_AUX_Kernel_Sdf_Syntax1_1sym = ATmakeSymbol ( "prod(id(\"Kernel-Sdf-Syntax\"),w(\"\"),[ql(\"syntax\"),w(\"\"),sort(\"Productions\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Grammar\"),w(\"\"),no-attrs)"
 , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Kernel_Sdf_Syntax1_1sym ) ;
lf_AUX_Kernel_Sdf_Syntax1_3sym = ATmakeSymbol ( "prod(id(\"Kernel-Sdf-Syntax\"),w(\"\"),[iter(sort(\"Production\"),w(\"\"),l(\"*\"))],w(\"\"),l(\"->\"),w(\"\"),sort(\"Productions\"),w(\"\"),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Kernel_Sdf_Syntax1_3sym ) ;
lf_AUX_Kernel_Sdf_Syntax1_2sym = ATmakeSymbol ( "listtype(sort(\"Production\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Kernel_Sdf_Syntax1_2sym ) ;
lf_AUX_Kernel_Sdf_Syntax1_4sym = ATmakeSymbol ( "prod(id(\"Kernel-Sdf-Syntax\"),w(\"\"),[sort(\"Symbols\"),w(\"\"),ql(\"->\"),w(\"\"),sort(\"Symbol\"),w(\"\"),sort(\"Attributes\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Production\"),w(\"\"),no-attrs)" , 3 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Kernel_Sdf_Syntax1_4sym ) ;
lf_AUX_Kernel_Sdf_Syntax1_5sym = ATmakeSymbol ( "prod(id(\"Kernel-Sdf-Syntax\"),w(\"\"),[],w(\"\"),l(\"->\"),w(\"\"),sort(\"Attributes\"),w(\"\"),no-attrs)" , 0 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Kernel_Sdf_Syntax1_5sym ) ;
lf_AUX_Kernel_Sdf_Syntax1_7sym = ATmakeSymbol ( "prod(id(\"Kernel-Sdf-Syntax\"),w(\"\"),[ql(\"{\"),w(\"\"),iter-sep(l(\"{\"),w(\"\"),sort(\"Attribute\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"*\")),w(\"\"),ql(\"}\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Attributes\"),w(\"\"),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Kernel_Sdf_Syntax1_7sym ) ;
lf_AUX_Kernel_Sdf_Syntax1_6sym = ATmakeSymbol ( "listtype(sort(\"Attribute\"),ql(\",\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Kernel_Sdf_Syntax1_6sym ) ;
register_prod ( ATparse ( "prod(id(\"Kernel-Sdf-Syntax\"),w(\"\"),[ql(\"syntax\"),w(\"\"),sort(\"Productions\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Grammar\"),w(\"\"),no-attrs)" ) , lf_AUX_Kernel_Sdf_Syntax1_1 , lf_AUX_Kernel_Sdf_Syntax1_1sym ) ;
register_prod ( ATparse ( "listtype(sort(\"Production\"))" ) , lf_AUX_Kernel_Sdf_Syntax1_2 , lf_AUX_Kernel_Sdf_Syntax1_2sym ) ;
register_prod ( ATparse ( "prod(id(\"Kernel-Sdf-Syntax\"),w(\"\"),[iter(sort(\"Production\"),w(\"\"),l(\"*\"))],w(\"\"),l(\"->\"),w(\"\"),sort(\"Productions\"),w(\"\"),no-attrs)" ) , lf_AUX_Kernel_Sdf_Syntax1_3 , lf_AUX_Kernel_Sdf_Syntax1_3sym ) ;
register_prod ( ATparse ( "prod(id(\"Kernel-Sdf-Syntax\"),w(\"\"),[sort(\"Symbols\"),w(\"\"),ql(\"->\"),w(\"\"),sort(\"Symbol\"),w(\"\"),sort(\"Attributes\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Production\"),w(\"\"),no-attrs)" ) , lf_AUX_Kernel_Sdf_Syntax1_4 , lf_AUX_Kernel_Sdf_Syntax1_4sym ) ;
register_prod ( ATparse ( "prod(id(\"Kernel-Sdf-Syntax\"),w(\"\"),[],w(\"\"),l(\"->\"),w(\"\"),sort(\"Attributes\"),w(\"\"),no-attrs)" ) , lf_AUX_Kernel_Sdf_Syntax1_5 , lf_AUX_Kernel_Sdf_Syntax1_5sym ) ;
register_prod ( ATparse ( "listtype(sort(\"Attribute\"),ql(\",\"))" ) , lf_AUX_Kernel_Sdf_Syntax1_6 , lf_AUX_Kernel_Sdf_Syntax1_6sym ) ;
register_prod ( ATparse ( "prod(id(\"Kernel-Sdf-Syntax\"),w(\"\"),[ql(\"{\"),w(\"\"),iter-sep(l(\"{\"),w(\"\"),sort(\"Attribute\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"*\")),w(\"\"),ql(\"}\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Attributes\"),w(\"\"),no-attrs)" ) , lf_AUX_Kernel_Sdf_Syntax1_7 , lf_AUX_Kernel_Sdf_Syntax1_7sym ) ;
}
void resolve_AUX_Kernel_Sdf_Syntax1 ( ) {
}
void init_AUX_Kernel_Sdf_Syntax1 ( ) {
}
ATerm lf_AUX_Kernel_Sdf_Syntax1_6 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Kernel_Sdf_Syntax1_6sym , ATmakeAppl ( lf_AUX_Kernel_Sdf_Syntax1_6sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Kernel_Sdf_Syntax1_6sym , arg0 ) ) ;
}
ATerm lf_AUX_Kernel_Sdf_Syntax1_7 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Kernel_Sdf_Syntax1_7sym , ATmakeAppl ( lf_AUX_Kernel_Sdf_Syntax1_7sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Kernel_Sdf_Syntax1_7sym , arg0 ) ) ;
}
ATerm lf_AUX_Kernel_Sdf_Syntax1_5 ( ) {
CONS_ENTRY ( lf_AUX_Kernel_Sdf_Syntax1_5sym , ATmakeAppl0 ( lf_AUX_Kernel_Sdf_Syntax1_5sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_AUX_Kernel_Sdf_Syntax1_5sym ) ) ;
}
ATerm lf_AUX_Kernel_Sdf_Syntax1_4 ( ATerm arg0 , ATerm arg1 , ATerm arg2 ) {
CONS_ENTRY ( lf_AUX_Kernel_Sdf_Syntax1_4sym , ATmakeAppl ( lf_AUX_Kernel_Sdf_Syntax1_4sym , arg0 , arg1 , arg2 ) ) ;
CONS_EXIT ( make_nf3 ( lf_AUX_Kernel_Sdf_Syntax1_4sym , arg0 , arg1 , arg2 ) ) ;
}
ATerm lf_AUX_Kernel_Sdf_Syntax1_2 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Kernel_Sdf_Syntax1_2sym , ATmakeAppl ( lf_AUX_Kernel_Sdf_Syntax1_2sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Kernel_Sdf_Syntax1_2sym , arg0 ) ) ;
}
ATerm lf_AUX_Kernel_Sdf_Syntax1_3 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Kernel_Sdf_Syntax1_3sym , ATmakeAppl ( lf_AUX_Kernel_Sdf_Syntax1_3sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Kernel_Sdf_Syntax1_3sym , arg0 ) ) ;
}
ATerm lf_AUX_Kernel_Sdf_Syntax1_1 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Kernel_Sdf_Syntax1_1sym , ATmakeAppl ( lf_AUX_Kernel_Sdf_Syntax1_1sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Kernel_Sdf_Syntax1_1sym , arg0 ) ) ;
}

