/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_Sdf2_to_ADT3_1sym ;
static ATerm lf_AUX_Sdf2_to_ADT3_1 ( ATerm arg1 ) ;
static Symbol ef1sym ;
static funcptr ef1 ;
static Symbol ef2sym ;
static funcptr ef2 ;
void register_AUX_Sdf2_to_ADT3 ( ) {
lf_AUX_Sdf2_to_ADT3_1sym = ATmakeSymbol ( "prod(id(\"Sdf2-to-ADT\"),w(\"\"),[ql(\"sdf-to-adt-cons-remove\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"SDF\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)"
 , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Sdf2_to_ADT3_1sym ) ;
register_prod ( ATparse ( "prod(id(\"Sdf2-to-ADT\"),w(\"\"),[ql(\"sdf-to-adt-cons-remove\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"SDF\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) , lf_AUX_Sdf2_to_ADT3_1 , lf_AUX_Sdf2_to_ADT3_1sym ) ;
}
void resolve_AUX_Sdf2_to_ADT3 ( ) {
ef1 = lookup_func ( ATreadFromString ( "prod(id(\"Sdf2-to-ADT\"),w(\"\"),[ql(\"sdf-to-adt\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"SDF\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"ConsOption\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef1sym = lookup_sym ( ATreadFromString ( "prod(id(\"Sdf2-to-ADT\"),w(\"\"),[ql(\"sdf-to-adt\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"SDF\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"ConsOption\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef2 = lookup_func ( ATreadFromString ( "prod(id(\"Cons-Options\"),w(\"\"),[ql(\"cons-remove\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ConsOption\"),w(\"\"),no-attrs)" ) ) ;
ef2sym = lookup_sym ( ATreadFromString ( "prod(id(\"Cons-Options\"),w(\"\"),[ql(\"cons-remove\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ConsOption\"),w(\"\"),no-attrs)" ) ) ;
}
void init_AUX_Sdf2_to_ADT3 ( ) {
}
ATerm lf_AUX_Sdf2_to_ADT3_1 ( ATerm arg0 ) {
FUNC_ENTRY ( lf_AUX_Sdf2_to_ADT3_1sym , ATmakeAppl ( lf_AUX_Sdf2_to_ADT3_1sym , arg0 ) ) ;
FUNC_EXIT ( ( * ef1 ) ( arg0 , ( * ef2 ) ( ) ) ) ;
FUNC_EXIT ( make_nf1 ( lf_AUX_Sdf2_to_ADT3_1sym , arg0 ) ) ;
}

