/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
void register_AUX_Sdf2_to_ADT1 ( ) {
}
void resolve_AUX_Sdf2_to_ADT1 ( ) {
}
void init_AUX_Sdf2_to_ADT1 ( ) {
}

