/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_Character_Syntax1_2sym ;
static ATerm lf_AUX_Character_Syntax1_2 ( ATerm arg1 ) ;
static Symbol lf_AUX_Character_Syntax1_1sym ;
static ATerm lf_AUX_Character_Syntax1_1 ( ATerm arg1 ) ;
static Symbol lf_AUX_Character_Syntax1_3sym ;
static ATerm lf_AUX_Character_Syntax1_3 ( ATerm arg1 ) ;
static Symbol lf_AUX_Character_Syntax1_4sym ;
static ATerm lf_AUX_Character_Syntax1_4 ( ) ;
static Symbol lf_AUX_Character_Syntax1_5sym ;
static ATerm lf_AUX_Character_Syntax1_5 ( ) ;
static Symbol lf_AUX_Character_Syntax1_6sym ;
static ATerm lf_AUX_Character_Syntax1_6 ( ATerm arg1 ) ;
static Symbol lf_AUX_Character_Syntax1_7sym ;
static ATerm lf_AUX_Character_Syntax1_7 ( ATerm arg1 ) ;
void register_AUX_Character_Syntax1 ( ) {
lf_AUX_Character_Syntax1_2sym = ATmakeSymbol ( "prod(id(\"GEN-LexConsFuncs\"),w(\"\"),[ql(\"shortchar\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"CHAR\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ShortChar\"),w(\"\"),no-attrs)"
 , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Character_Syntax1_2sym ) ;
lf_AUX_Character_Syntax1_1sym = ATmakeSymbol ( "listtype(sort(\"CHAR\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Character_Syntax1_1sym ) ;
lf_AUX_Character_Syntax1_3sym = ATmakeSymbol ( "prod(id(\"GEN-LexConsFuncs\"),w(\"\"),[ql(\"numchar\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"CHAR\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"NumChar\"),w(\"\"),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Character_Syntax1_3sym ) ;
lf_AUX_Character_Syntax1_4sym = ATmakeSymbol ( "prod(id(\"Character-Syntax\"),w(\"\"),[ql(\"\\\\\\\\EOF\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Character\"),w(\"\"),no-attrs)" , 0 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Character_Syntax1_4sym ) ;
lf_AUX_Character_Syntax1_5sym = ATmakeSymbol ( "prod(id(\"Character-Syntax\"),w(\"\"),[ql(\"\\\\\\\\TOP\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Character\"),w(\"\"),no-attrs)" , 0 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Character_Syntax1_5sym ) ;
lf_AUX_Character_Syntax1_6sym = ATmakeSymbol ( "prod(id(\"Character-Syntax\"),w(\"\"),[sort(\"ShortChar\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Character\"),w(\"\"),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Character_Syntax1_6sym ) ;
lf_AUX_Character_Syntax1_7sym = ATmakeSymbol ( "prod(id(\"Character-Syntax\"),w(\"\"),[sort(\"NumChar\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Character\"),w(\"\"),no-attrs)" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Character_Syntax1_7sym ) ;
register_prod ( ATparse ( "listtype(sort(\"CHAR\"))" ) , lf_AUX_Character_Syntax1_1 , lf_AUX_Character_Syntax1_1sym ) ;
register_prod ( ATparse ( "prod(id(\"GEN-LexConsFuncs\"),w(\"\"),[ql(\"shortchar\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"CHAR\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ShortChar\"),w(\"\"),no-attrs)" ) , lf_AUX_Character_Syntax1_2 , lf_AUX_Character_Syntax1_2sym ) ;
register_prod ( ATparse ( "prod(id(\"GEN-LexConsFuncs\"),w(\"\"),[ql(\"numchar\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"CHAR\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"NumChar\"),w(\"\"),no-attrs)" ) , lf_AUX_Character_Syntax1_3 , lf_AUX_Character_Syntax1_3sym ) ;
register_prod ( ATparse ( "prod(id(\"Character-Syntax\"),w(\"\"),[ql(\"\\\\\\\\EOF\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Character\"),w(\"\"),no-attrs)" ) , lf_AUX_Character_Syntax1_4 , lf_AUX_Character_Syntax1_4sym ) ;
register_prod ( ATparse ( "prod(id(\"Character-Syntax\"),w(\"\"),[ql(\"\\\\\\\\TOP\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Character\"),w(\"\"),no-attrs)" ) , lf_AUX_Character_Syntax1_5 , lf_AUX_Character_Syntax1_5sym ) ;
register_prod ( ATparse ( "prod(id(\"Character-Syntax\"),w(\"\"),[sort(\"ShortChar\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Character\"),w(\"\"),no-attrs)" ) , lf_AUX_Character_Syntax1_6 , lf_AUX_Character_Syntax1_6sym ) ;
register_prod ( ATparse ( "prod(id(\"Character-Syntax\"),w(\"\"),[sort(\"NumChar\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Character\"),w(\"\"),no-attrs)" ) , lf_AUX_Character_Syntax1_7 , lf_AUX_Character_Syntax1_7sym ) ;
}
void resolve_AUX_Character_Syntax1 ( ) {
}
void init_AUX_Character_Syntax1 ( ) {
}
ATerm lf_AUX_Character_Syntax1_7 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Character_Syntax1_7sym , ATmakeAppl ( lf_AUX_Character_Syntax1_7sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Character_Syntax1_7sym , arg0 ) ) ;
}
ATerm lf_AUX_Character_Syntax1_6 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Character_Syntax1_6sym , ATmakeAppl ( lf_AUX_Character_Syntax1_6sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Character_Syntax1_6sym , arg0 ) ) ;
}
ATerm lf_AUX_Character_Syntax1_5 ( ) {
CONS_ENTRY ( lf_AUX_Character_Syntax1_5sym , ATmakeAppl0 ( lf_AUX_Character_Syntax1_5sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_AUX_Character_Syntax1_5sym ) ) ;
}
ATerm lf_AUX_Character_Syntax1_4 ( ) {
CONS_ENTRY ( lf_AUX_Character_Syntax1_4sym , ATmakeAppl0 ( lf_AUX_Character_Syntax1_4sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_AUX_Character_Syntax1_4sym ) ) ;
}
ATerm lf_AUX_Character_Syntax1_3 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Character_Syntax1_3sym , ATmakeAppl ( lf_AUX_Character_Syntax1_3sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Character_Syntax1_3sym , arg0 ) ) ;
}
ATerm lf_AUX_Character_Syntax1_1 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Character_Syntax1_1sym , ATmakeAppl ( lf_AUX_Character_Syntax1_1sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Character_Syntax1_1sym , arg0 ) ) ;
}
ATerm lf_AUX_Character_Syntax1_2 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Character_Syntax1_2sym , ATmakeAppl ( lf_AUX_Character_Syntax1_2sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Character_Syntax1_2sym , arg0 ) ) ;
}

