/**
 * This file is generated by ../toolbus/ctif. Do not edit!
 * Generated from tifs for tool 'tool2'
 * Headerfile generated at Mon May 25 18:19:40 1998
 */

#ifndef _tool2_H
#define _tool2_H

#include <aterm1.h>

/* Prototypes for functions called from the event handler */
void rec_terminate(int conn, ATerm t)
{
	ATprintf("rec_terminate called: %d, %t\n", conn, t);
}

void rec_ack_event(int conn, ATerm t)
{
}

void start_events(int conn)
{
}

ATerm test_eval_3(int conn, int, ATerm t)
{
}

ATerm test_eval_2(int conn, char *s)
{
}

ATerm test_eval_1(int conn)
{
}

ATerm test_eval_0(int conn)
{
}

void test_do_3(int conn, ATerm, ATerm)
{
}

void test_do_2(int conn, ATerm)
{
}

void test_do_2(int conn, ATerm)
{
}

void test_do_1(int conn)
{
}

void test_do_0(int conn)
{
}

#endif
