/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
void register_AUX_Character_Class_Membership1 ( ) {
}
void resolve_AUX_Character_Class_Membership1 ( ) {
}
void init_AUX_Character_Class_Membership1 ( ) {
}

