/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_Sdf2_to_AsFix2ME_ADT5_1sym ;
static ATerm lf_AUX_Sdf2_to_AsFix2ME_ADT5_1 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol ef1sym ;
static funcptr ef1 ;
void register_AUX_Sdf2_to_AsFix2ME_ADT5 ( ) {
lf_AUX_Sdf2_to_AsFix2ME_ADT5_1sym = ATmakeSymbol ( "prod(id(\"Sdf2-to-AsFix2ME-ADT\"),w(\"\"),[ql(\"sdf-to-asfix2me-adt\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Module\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"ConsOption\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)"
 , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Sdf2_to_AsFix2ME_ADT5_1sym ) ;
register_prod ( ATparse ( "prod(id(\"Sdf2-to-AsFix2ME-ADT\"),w(\"\"),[ql(\"sdf-to-asfix2me-adt\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Module\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"ConsOption\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) , lf_AUX_Sdf2_to_AsFix2ME_ADT5_1 , lf_AUX_Sdf2_to_AsFix2ME_ADT5_1sym ) ;
}
void resolve_AUX_Sdf2_to_AsFix2ME_ADT5 ( ) {
ef1 = lookup_func ( ATreadFromString ( "prod(id(\"Sdf2-to-AsFix2ME-ADT\"),w(\"\"),[ql(\"sdf-module-to-asfix2me-adt\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Module\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"ConsOption\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef1sym = lookup_sym ( ATreadFromString ( "prod(id(\"Sdf2-to-AsFix2ME-ADT\"),w(\"\"),[ql(\"sdf-module-to-asfix2me-adt\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"Module\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"ConsOption\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
}
void init_AUX_Sdf2_to_AsFix2ME_ADT5 ( ) {
}
ATerm lf_AUX_Sdf2_to_AsFix2ME_ADT5_1 ( ATerm arg0 , ATerm arg1 ) {
FUNC_ENTRY ( lf_AUX_Sdf2_to_AsFix2ME_ADT5_1sym , ATmakeAppl ( lf_AUX_Sdf2_to_AsFix2ME_ADT5_1sym , arg0 , arg1 ) ) ;
FUNC_EXIT ( ( * ef1 ) ( arg0 , arg1 ) ) ;
FUNC_EXIT ( make_nf2 ( lf_AUX_Sdf2_to_AsFix2ME_ADT5_1sym , arg0 , arg1 ) ) ;
}

