/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_Build_AsFix2ME_ADT3_2_recursivesym ;
static ATerm lf_AUX_Build_AsFix2ME_ADT3_2_recursive ( ATerm arg1 , ATerm arg2 ) ;
static Symbol lf_AUX_Build_AsFix2ME_ADT3_2sym ;
static ATerm lf_AUX_Build_AsFix2ME_ADT3_2 ( ATerm arg1 , ATerm arg2 ) ;
static Symbol ef4sym ;
static funcptr ef4 ;
static Symbol ef5sym ;
static funcptr ef5 ;
static Symbol lf3sym ;
static ATerm lf3 ( ATerm arg1 ) ;
static Symbol ef1sym ;
static funcptr ef1 ;
static Symbol ef3sym ;
static funcptr ef3 ;
static Symbol lf_AUX_Build_AsFix2ME_ADT3_1sym ;
static ATerm lf_AUX_Build_AsFix2ME_ADT3_1 ( ATerm arg1 ) ;
static Symbol ef2sym ;
static funcptr ef2 ;
static Symbol lf4sym ;
static ATerm lf4 ( ATerm arg1 ) ;
void register_AUX_Build_AsFix2ME_ADT3 ( ) {
lf_AUX_Build_AsFix2ME_ADT3_2_recursivesym = ATmakeSymbol ( "prod(id(\"Build-AsFix2ME-ADT\"),w(\"\"),[ql(\"build-asfix-prod-args\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"AFun\"),w(\"\"),ql(\",\"),w(\"\"),iter(sort(\"Symbol\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)"
 , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Build_AsFix2ME_ADT3_2_recursivesym ) ;
lf_AUX_Build_AsFix2ME_ADT3_2sym = ATmakeSymbol ( "prod(id(\"Build-AsFix2ME-ADT\"),w(\"\"),[ql(\"build-asfix-prod-args\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"AFun\"),w(\"\"),ql(\",\"),w(\"\"),iter(sort(\"Symbol\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" , 2 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Build_AsFix2ME_ADT3_2sym ) ;
lf3sym = ATmakeSymbol ( "listtype(sort(\"CHAR\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf3sym ) ;
lf_AUX_Build_AsFix2ME_ADT3_1sym = ATmakeSymbol ( "listtype(sort(\"Symbol\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Build_AsFix2ME_ADT3_1sym ) ;
lf4sym = ATmakeSymbol ( "listtype(sort(\"ATerm\"),ql(\",\"))" , 1 , ATtrue ) ;
ATprotectSymbol ( lf4sym ) ;
register_prod ( ATparse ( "listtype(sort(\"Symbol\"))" ) , lf_AUX_Build_AsFix2ME_ADT3_1 , lf_AUX_Build_AsFix2ME_ADT3_1sym ) ;
register_prod ( ATparse ( "prod(id(\"Build-AsFix2ME-ADT\"),w(\"\"),[ql(\"build-asfix-prod-args\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"AFun\"),w(\"\"),ql(\",\"),w(\"\"),iter(sort(\"Symbol\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" ) , lf_AUX_Build_AsFix2ME_ADT3_2 , lf_AUX_Build_AsFix2ME_ADT3_2sym ) ;
register_prod ( ATparse ( "prod(id(\"Build-AsFix2ME-ADT\"),w(\"\"),[ql(\"build-asfix-prod-args\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"AFun\"),w(\"\"),ql(\",\"),w(\"\"),iter(sort(\"Symbol\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),no-attrs)" ) , lf_AUX_Build_AsFix2ME_ADT3_2_recursive , lf_AUX_Build_AsFix2ME_ADT3_2_recursivesym ) ;
register_prod ( ATparse ( "listtype(sort(\"CHAR\"))" ) , lf3 , lf3sym ) ;
register_prod ( ATparse ( "listtype(sort(\"ATerm\"),ql(\",\"))" ) , lf4 , lf4sym ) ;
}
void resolve_AUX_Build_AsFix2ME_ADT3 ( ) {
ef1 = lookup_func ( ATreadFromString ( "prod(id(\"GEN-LexConsFuncs\"),w(\"\"),[ql(\"afun\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"CHAR\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef1sym = lookup_sym ( ATreadFromString ( "prod(id(\"GEN-LexConsFuncs\"),w(\"\"),[ql(\"afun\"),w(\"\"),ql(\"(\"),w(\"\"),iter(sort(\"CHAR\"),w(\"\"),l(\"*\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"AFun\"),w(\"\"),no-attrs)" ) ) ;
ef2 = lookup_func ( ATreadFromString ( "prod(id(\"ATerm-Syntax\"),w(\"\"),[iter-sep(l(\"{\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"*\"))],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"avoid\")],w(\"\"),l(\"}\")))" ) ) ;
ef2sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerm-Syntax\"),w(\"\"),[iter-sep(l(\"{\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"*\"))],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerms\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"avoid\")],w(\"\"),l(\"}\")))" ) ) ;
ef3 = lookup_func ( ATreadFromString ( "prod(id(\"Build-AsFix2ME-ADT\"),w(\"\"),[ql(\"build-asfix-prod-arg\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"AFun\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"Symbol\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef3sym = lookup_sym ( ATreadFromString ( "prod(id(\"Build-AsFix2ME-ADT\"),w(\"\"),[ql(\"build-asfix-prod-arg\"),w(\"\"),ql(\"(\"),w(\"\"),sort(\"AFun\"),w(\"\"),ql(\",\"),w(\"\"),sort(\"Symbol\"),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),no-attrs)" ) ) ;
ef4 = lookup_func ( ATreadFromString ( "prod(id(\"ATerm-Syntax\"),w(\"\"),[sort(\"AFun\"),w(\"\"),ql(\"(\"),w(\"\"),iter-sep(l(\"{\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"+\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"constructor\")],w(\"\"),l(\"}\")))" ) ) ;
ef4sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerm-Syntax\"),w(\"\"),[sort(\"AFun\"),w(\"\"),ql(\"(\"),w(\"\"),iter-sep(l(\"{\"),w(\"\"),sort(\"ATerm\"),w(\"\"),ql(\",\"),w(\"\"),l(\"}\"),w(\"\"),l(\"+\")),w(\"\"),ql(\")\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"constructor\")],w(\"\"),l(\"}\")))" ) ) ;
ef5 = lookup_func ( ATreadFromString ( "prod(id(\"ATerm-Syntax\"),w(\"\"),[sort(\"AFun\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"constructor\")],w(\"\"),l(\"}\")))" ) ) ;
ef5sym = lookup_sym ( ATreadFromString ( "prod(id(\"ATerm-Syntax\"),w(\"\"),[sort(\"AFun\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"ATerm\"),w(\"\"),attrs(l(\"{\"),w(\"\"),[l(\"constructor\")],w(\"\"),l(\"}\")))" ) ) ;
}
static ATerm constant0 = NULL ;
void init_AUX_Build_AsFix2ME_ADT3 ( ) {
ATprotect ( & constant0 ) ;
}
ATerm lf_AUX_Build_AsFix2ME_ADT3_2 ( ATerm arg0 , ATerm arg1 ) {
{
ATerm tmp [ 9 ] ;
FUNC_ENTRY ( lf_AUX_Build_AsFix2ME_ADT3_2sym , ATmakeAppl ( lf_AUX_Build_AsFix2ME_ADT3_2sym , arg0 , arg1 ) ) ;
if ( check_sym ( arg0 , ef1sym ) ) {
{
ATerm atmp00 = arg_0 ( arg0 ) ;
if ( check_sym ( atmp00 , lf3sym ) ) {
{
ATerm atmp000 = arg_0 ( atmp00 ) ;
if ( check_sym ( arg1 , lf_AUX_Build_AsFix2ME_ADT3_1sym ) ) {
{
ATerm atmp10 = arg_0 ( arg1 ) ;
if ( not_empty_list ( atmp000 ) ) {
( tmp [ 0 ] = list_head ( atmp000 ) ) ;
if ( term_equal ( tmp [ 0 ] , make_char ( 108 ) ) ) {
( tmp [ 1 ] = list_tail ( atmp000 ) ) ;
if ( not_empty_list ( tmp [ 1 ] ) ) {
if ( term_equal ( list_head ( tmp [ 1 ] ) , make_char ( 101 ) ) ) {
( tmp [ 2 ] = list_tail ( tmp [ 1 ] ) ) ;
if ( is_single_element ( tmp [ 2 ] ) ) {
if ( term_equal ( list_head ( tmp [ 2 ] ) , make_char ( 120 ) ) ) {
if ( not_empty_list ( atmp10 ) ) {
( tmp [ 3 ] = list_head ( atmp10 ) ) ;
( tmp [ 4 ] = list_tail ( atmp10 ) ) ;
if ( not_empty_list ( tmp [ 4 ] ) ) {
( tmp [ 5 ] = ( * ef3 ) ( ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 3 , char_table [ 108 ] , char_table [ 101 ] , char_table [ 120 ] ) ) ) , tmp [ 3 ] ) ) ;
( tmp [ 6 ] = lf_AUX_Build_AsFix2ME_ADT3_2 ( ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 3 , char_table [ 108 ] , char_table [ 101 ] , char_table [ 120 ] ) ) ) , lf_AUX_Build_AsFix2ME_ADT3_1 ( make_list ( tmp [ 4 ] ) ) ) ) ;
if ( check_sym ( tmp [ 6 ] , ef2sym ) ) {
( tmp [ 7 ] = arg_0 ( tmp [ 6 ] ) ) ;
if ( check_sym ( tmp [ 7 ] , lf4sym ) ) {
( tmp [ 8 ] = arg_0 ( tmp [ 7 ] ) ) ;
FUNC_EXIT ( ( * ef2 ) ( lf4 ( cons ( make_list ( tmp [ 5 ] ) , make_list ( tmp [ 8 ] ) ) ) ) ) ;
}
}
}
}
}
}
}
}
}
if ( term_equal ( tmp [ 0 ] , make_char ( 99 ) ) ) {
( tmp [ 1 ] = list_tail ( atmp000 ) ) ;
if ( is_single_element ( tmp [ 1 ] ) ) {
if ( term_equal ( list_head ( tmp [ 1 ] ) , make_char ( 102 ) ) ) {
if ( not_empty_list ( atmp10 ) ) {
( tmp [ 2 ] = list_head ( atmp10 ) ) ;
( tmp [ 3 ] = list_tail ( atmp10 ) ) ;
if ( not_empty_list ( tmp [ 3 ] ) ) {
( tmp [ 4 ] = ( * ef3 ) ( ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 2 , char_table [ 99 ] , char_table [ 102 ] ) ) ) , tmp [ 2 ] ) ) ;
( tmp [ 5 ] = lf_AUX_Build_AsFix2ME_ADT3_2 ( ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 2 , char_table [ 99 ] , char_table [ 102 ] ) ) ) , lf_AUX_Build_AsFix2ME_ADT3_1 ( make_list ( tmp [ 3 ] ) ) ) ) ;
if ( check_sym ( tmp [ 5 ] , ef2sym ) ) {
( tmp [ 6 ] = arg_0 ( tmp [ 5 ] ) ) ;
if ( check_sym ( tmp [ 6 ] , lf4sym ) ) {
( tmp [ 7 ] = arg_0 ( tmp [ 6 ] ) ) ;
FUNC_EXIT ( ( * ef2 ) ( lf4 ( cons ( make_list ( tmp [ 4 ] ) , cons ( make_list ( make_nf2 ( ef4sym , ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 2 , char_table [ 99 ] , char_table [ 102 ] ) ) ) , lf4 ( make_list ( make_nf2 ( ef4sym , ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 3 , char_table [ 111 ] , char_table [ 112 ] , char_table [ 116 ] ) ) ) , lf4 ( make_list ( make_nf1 ( ef5sym , ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 6 , char_table [ 108 ] , char_table [ 97 ] , char_table [ 121 ] , char_table [ 111 ] , char_table [ 117 ] , char_table [ 116 ] ) ) ) ) ) ) ) ) ) ) ) , make_list ( tmp [ 7 ] ) ) ) ) ) ) ;
}
}
}
}
}
}
}
}
}
}
}
}
}
}
if ( check_sym ( arg1 , lf_AUX_Build_AsFix2ME_ADT3_1sym ) ) {
{
ATerm atmp10 = arg_0 ( arg1 ) ;
if ( ! not_empty_list ( atmp10 ) ) {
FUNC_EXIT_CONST ( constant0 , ( * ef2 ) ( lf4 ( make_list ( null ( ) ) ) ) ) ;
}
if ( is_single_element ( atmp10 ) ) {
( tmp [ 0 ] = list_head ( atmp10 ) ) ;
FUNC_EXIT ( ( * ef2 ) ( lf4 ( make_list ( ( * ef3 ) ( arg0 , tmp [ 0 ] ) ) ) ) ) ;
}
}
}
FUNC_EXIT ( make_nf2 ( lf_AUX_Build_AsFix2ME_ADT3_2sym , arg0 , arg1 ) ) ;
}
}
ATerm lf_AUX_Build_AsFix2ME_ADT3_2_recursive ( ATerm arg0 , ATerm arg1 ) {
{
ATerm tmp [ 9 ] ;
FUNC_ENTRY ( lf_AUX_Build_AsFix2ME_ADT3_2_recursivesym , ATmakeAppl ( lf_AUX_Build_AsFix2ME_ADT3_2_recursivesym , arg0 , arg1 ) ) ;
if ( check_sym ( arg0 , ef1sym ) ) {
{
ATerm atmp00 = arg_0 ( arg0 ) ;
if ( check_sym ( atmp00 , lf3sym ) ) {
{
ATerm atmp000 = arg_0 ( atmp00 ) ;
{
ATerm atmp10 = arg1 ;
if ( not_empty_list ( atmp000 ) ) {
( tmp [ 0 ] = list_head ( atmp000 ) ) ;
if ( term_equal ( tmp [ 0 ] , make_char ( 108 ) ) ) {
( tmp [ 1 ] = list_tail ( atmp000 ) ) ;
if ( not_empty_list ( tmp [ 1 ] ) ) {
if ( term_equal ( list_head ( tmp [ 1 ] ) , make_char ( 101 ) ) ) {
( tmp [ 2 ] = list_tail ( tmp [ 1 ] ) ) ;
if ( is_single_element ( tmp [ 2 ] ) ) {
if ( term_equal ( list_head ( tmp [ 2 ] ) , make_char ( 120 ) ) ) {
if ( not_empty_list ( atmp10 ) ) {
( tmp [ 3 ] = list_head ( atmp10 ) ) ;
( tmp [ 4 ] = list_tail ( atmp10 ) ) ;
if ( not_empty_list ( tmp [ 4 ] ) ) {
( tmp [ 5 ] = ( * ef3 ) ( ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 3 , char_table [ 108 ] , char_table [ 101 ] , char_table [ 120 ] ) ) ) , tmp [ 3 ] ) ) ;
( tmp [ 6 ] = lf_AUX_Build_AsFix2ME_ADT3_2 ( ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 3 , char_table [ 108 ] , char_table [ 101 ] , char_table [ 120 ] ) ) ) , lf_AUX_Build_AsFix2ME_ADT3_1 ( make_list ( tmp [ 4 ] ) ) ) ) ;
if ( check_sym ( tmp [ 6 ] , ef2sym ) ) {
( tmp [ 7 ] = arg_0 ( tmp [ 6 ] ) ) ;
if ( check_sym ( tmp [ 7 ] , lf4sym ) ) {
( tmp [ 8 ] = arg_0 ( tmp [ 7 ] ) ) ;
FUNC_EXIT ( ( * ef2 ) ( lf4 ( cons ( make_list ( tmp [ 5 ] ) , make_list ( tmp [ 8 ] ) ) ) ) ) ;
}
}
}
}
}
}
}
}
}
if ( term_equal ( tmp [ 0 ] , make_char ( 99 ) ) ) {
( tmp [ 1 ] = list_tail ( atmp000 ) ) ;
if ( is_single_element ( tmp [ 1 ] ) ) {
if ( term_equal ( list_head ( tmp [ 1 ] ) , make_char ( 102 ) ) ) {
if ( not_empty_list ( atmp10 ) ) {
( tmp [ 2 ] = list_head ( atmp10 ) ) ;
( tmp [ 3 ] = list_tail ( atmp10 ) ) ;
if ( not_empty_list ( tmp [ 3 ] ) ) {
( tmp [ 4 ] = ( * ef3 ) ( ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 2 , char_table [ 99 ] , char_table [ 102 ] ) ) ) , tmp [ 2 ] ) ) ;
( tmp [ 5 ] = lf_AUX_Build_AsFix2ME_ADT3_2 ( ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 2 , char_table [ 99 ] , char_table [ 102 ] ) ) ) , lf_AUX_Build_AsFix2ME_ADT3_1 ( make_list ( tmp [ 3 ] ) ) ) ) ;
if ( check_sym ( tmp [ 5 ] , ef2sym ) ) {
( tmp [ 6 ] = arg_0 ( tmp [ 5 ] ) ) ;
if ( check_sym ( tmp [ 6 ] , lf4sym ) ) {
( tmp [ 7 ] = arg_0 ( tmp [ 6 ] ) ) ;
FUNC_EXIT ( ( * ef2 ) ( lf4 ( cons ( make_list ( tmp [ 4 ] ) , cons ( make_list ( make_nf2 ( ef4sym , ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 2 , char_table [ 99 ] , char_table [ 102 ] ) ) ) , lf4 ( make_list ( make_nf2 ( ef4sym , ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 3 , char_table [ 111 ] , char_table [ 112 ] , char_table [ 116 ] ) ) ) , lf4 ( make_list ( make_nf1 ( ef5sym , ( * ef1 ) ( lf3 ( ( ATerm ) ATmakeList ( 6 , char_table [ 108 ] , char_table [ 97 ] , char_table [ 121 ] , char_table [ 111 ] , char_table [ 117 ] , char_table [ 116 ] ) ) ) ) ) ) ) ) ) ) ) , make_list ( tmp [ 7 ] ) ) ) ) ) ) ;
}
}
}
}
}
}
}
}
}
}
}
}
}
{
ATerm atmp10 = arg1 ;
if ( ! not_empty_list ( atmp10 ) ) {
FUNC_EXIT_CONST ( constant0 , ( * ef2 ) ( lf4 ( make_list ( null ( ) ) ) ) ) ;
}
if ( is_single_element ( atmp10 ) ) {
( tmp [ 0 ] = list_head ( atmp10 ) ) ;
FUNC_EXIT ( ( * ef2 ) ( lf4 ( make_list ( ( * ef3 ) ( arg0 , tmp [ 0 ] ) ) ) ) ) ;
}
}
FUNC_EXIT ( make_nf2 ( lf_AUX_Build_AsFix2ME_ADT3_2_recursivesym , arg0 , lf_AUX_Build_AsFix2ME_ADT3_1 ( arg1 ) ) ) ;
}
}
ATerm lf4 ( ATerm arg0 ) {
CONS_ENTRY ( lf4sym , ATmakeAppl ( lf4sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf4sym , arg0 ) ) ;
}
ATerm lf_AUX_Build_AsFix2ME_ADT3_1 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Build_AsFix2ME_ADT3_1sym , ATmakeAppl ( lf_AUX_Build_AsFix2ME_ADT3_1sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Build_AsFix2ME_ADT3_1sym , arg0 ) ) ;
}
ATerm lf3 ( ATerm arg0 ) {
CONS_ENTRY ( lf3sym , ATmakeAppl ( lf3sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf3sym , arg0 ) ) ;
}

