/* This C code is generated by the AsfSdfCompiler version 1.3 */

#include  "asc-support.h"
static Symbol lf_AUX_Character_Class_Normalization1_1sym ;
static ATerm lf_AUX_Character_Class_Normalization1_1 ( ATerm arg1 ) ;
static Symbol lf_AUX_Character_Class_Normalization1_2sym ;
static ATerm lf_AUX_Character_Class_Normalization1_2 ( ) ;
void register_AUX_Character_Class_Normalization1 ( ) {
lf_AUX_Character_Class_Normalization1_1sym = ATmakeSymbol ( "prod(id(\"Character-Class-Normalization\"),w(\"\"),[ql(\"<\"),w(\"\"),sort(\"CharRange\"),w(\"\"),ql(\">\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Result\"),w(\"\"),no-attrs)"
 , 1 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Character_Class_Normalization1_1sym ) ;
lf_AUX_Character_Class_Normalization1_2sym = ATmakeSymbol ( "prod(id(\"Character-Class-Normalization\"),w(\"\"),[ql(\"(/)\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"CharRange\"),w(\"\"),no-attrs)" , 0 , ATtrue ) ;
ATprotectSymbol ( lf_AUX_Character_Class_Normalization1_2sym ) ;
register_prod ( ATparse ( "prod(id(\"Character-Class-Normalization\"),w(\"\"),[ql(\"<\"),w(\"\"),sort(\"CharRange\"),w(\"\"),ql(\">\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"Result\"),w(\"\"),no-attrs)" ) , lf_AUX_Character_Class_Normalization1_1 , lf_AUX_Character_Class_Normalization1_1sym ) ;
register_prod ( ATparse ( "prod(id(\"Character-Class-Normalization\"),w(\"\"),[ql(\"(/)\")],w(\"\"),l(\"->\"),w(\"\"),sort(\"CharRange\"),w(\"\"),no-attrs)" ) , lf_AUX_Character_Class_Normalization1_2 , lf_AUX_Character_Class_Normalization1_2sym ) ;
}
void resolve_AUX_Character_Class_Normalization1 ( ) {
}
void init_AUX_Character_Class_Normalization1 ( ) {
}
ATerm lf_AUX_Character_Class_Normalization1_2 ( ) {
CONS_ENTRY ( lf_AUX_Character_Class_Normalization1_2sym , ATmakeAppl0 ( lf_AUX_Character_Class_Normalization1_2sym ) ) ;
CONS_EXIT ( make_nf0 ( lf_AUX_Character_Class_Normalization1_2sym ) ) ;
}
ATerm lf_AUX_Character_Class_Normalization1_1 ( ATerm arg0 ) {
CONS_ENTRY ( lf_AUX_Character_Class_Normalization1_1sym , ATmakeAppl ( lf_AUX_Character_Class_Normalization1_1sym , arg0 ) ) ;
CONS_EXIT ( make_nf1 ( lf_AUX_Character_Class_Normalization1_1sym , arg0 ) ) ;
}

